
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmartphoneXMLService", targetNamespace = "http://generated/", wsdlLocation = "http://localhost:8081/addsmartphonesoap?wsdl")
public class SmartphoneXMLService
    extends Service
{

    private final static URL SMARTPHONEXMLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMARTPHONEXMLSERVICE_EXCEPTION;
    private final static QName SMARTPHONEXMLSERVICE_QNAME = new QName("http://generated/", "SmartphoneXMLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/addsmartphonesoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMARTPHONEXMLSERVICE_WSDL_LOCATION = url;
        SMARTPHONEXMLSERVICE_EXCEPTION = e;
    }

    public SmartphoneXMLService() {
        super(__getWsdlLocation(), SMARTPHONEXMLSERVICE_QNAME);
    }

    public SmartphoneXMLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMARTPHONEXMLSERVICE_QNAME, features);
    }

    public SmartphoneXMLService(URL wsdlLocation) {
        super(wsdlLocation, SMARTPHONEXMLSERVICE_QNAME);
    }

    public SmartphoneXMLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMARTPHONEXMLSERVICE_QNAME, features);
    }

    public SmartphoneXMLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmartphoneXMLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmartphoneXML
     */
    @WebEndpoint(name = "SmartphoneXMLPort")
    public SmartphoneXML getSmartphoneXMLPort() {
        return super.getPort(new QName("http://generated/", "SmartphoneXMLPort"), SmartphoneXML.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmartphoneXML
     */
    @WebEndpoint(name = "SmartphoneXMLPort")
    public SmartphoneXML getSmartphoneXMLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://generated/", "SmartphoneXMLPort"), SmartphoneXML.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMARTPHONEXMLSERVICE_EXCEPTION!= null) {
            throw SMARTPHONEXMLSERVICE_EXCEPTION;
        }
        return SMARTPHONEXMLSERVICE_WSDL_LOCATION;
    }

}
