
package add_smartphone_artifact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Smartphone", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Smartphone {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setXML", targetNamespace = "http://soap/", className = "add_smartphone_artifact.SetXML")
    @ResponseWrapper(localName = "setXMLResponse", targetNamespace = "http://soap/", className = "add_smartphone_artifact.SetXMLResponse")
    public String setXML(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
